name: Unit Tests

on: push

jobs:
  test:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-ex_check-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-ex_check-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-ex_check-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-ex_check-
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.8
          elixir-version: 1.10.1
      - run: mix deps.get
      - run: MIX_ENV=dev mix check --except ex_unit --except dialyzer
